# Generated by Django 4.1.1 on 2022-09-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=40, verbose_name="LastName")),
                (
                    "first_name",
                    models.CharField(max_length=40, verbose_name="FirstName"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("number", models.IntegerField(verbose_name="Number")),
                (
                    "sent_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и Время"
                    ),
                ),
            ],
        ),
    ]
